<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DeliveryMenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('delivery_men')->insert([

            [
                'id' => 1,
                'first_name' => 'Roshan',
                'last_name' => 'Yadav',
                'phone' => '8928339535',
                'email' => 'roshan.yadav@example.com',
                'dob' => '1992-04-15',
                'gender' => 'Male',
                'current_address' => 'Andheri East',
                'city' => 'Mumbai',
                'state' => 'Maharashtra',
                'country' => 'India',
                'pincode' => '400059',
                'employment_type' => 'Full-Time',
                'joining_date' => '2022-01-10',
                'assigned_area' => 'ABC',
                'vehicle_type' => 'Bike',
                'vehical_no' => 'MH02AB1234',
                'driving_license_no' => 'MHDL20224567',
                'driving_license' => null,
                'police_verification' => 'Yes',
                'police_verification_status' => 'Completed',
                'police_certificate' => null,
                'govid' => 'Aadhar',
                'idno' => '123456789012',
                'adhar_pic' => null,
                'bank_acc_no' => '123456789012',
                'bank_name' => 'HDFC Bank',
                'ifsc_code' => 'HDFC0001234',
                'passbook_pic' => null,
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'otp' => null,
                'otp_expiry' => null,
            ],

            [
                'id' => 2,
                'first_name' => 'Saurabh',
                'last_name' => 'Damale',
                'phone' => '7709131547',
                'email' => 'saurabh.damale@example.com',
                'dob' => '1990-09-20',
                'gender' => 'Male',
                'current_address' => 'BTM Layout',
                'city' => 'Bengaluru',
                'state' => 'Karnataka',
                'country' => 'India',
                'pincode' => '560076',
                'employment_type' => 'Part-Time',
                'joining_date' => '2021-10-05',
                'assigned_area' => 'ABC',
                'vehicle_type' => 'Scooter',
                'vehical_no' => 'KA05EF7890',
                'driving_license_no' => 'KADL56782345',
                'driving_license' => null,
                'police_verification' => 'Yes',
                'police_verification_status' => 'Completed',
                'police_certificate' => null,
                'govid' => 'PAN',
                'idno' => 'ABCDE1234F',
                'adhar_pic' => null,
                'bank_acc_no' => '567890123456',
                'bank_name' => 'SBI Bank',
                'ifsc_code' => 'SBIN0005678',
                'passbook_pic' => null,
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'otp' => null,
                'otp_expiry' => null,
            ],

            [
                'id' => 3,
                'first_name' => 'Mayur',
                'last_name' => 'Satam',
                'phone' => '8591483531',
                'email' => 'mayur.satam@example.com',
                'dob' => '1994-12-25',
                'gender' => 'Male',
                'current_address' => 'Charminar Area',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'country' => 'India',
                'pincode' => '500002',
                'employment_type' => 'Full-Time',
                'joining_date' => '2023-03-12',
                'assigned_area' => 'ABC',
                'vehicle_type' => 'Bike',
                'vehical_no' => 'TS09FG4321',
                'driving_license_no' => 'TSDL98765432',
                'driving_license' => null,
                'police_verification' => 'Yes',
                'police_verification_status' => 'Completed',
                'police_certificate' => null,
                'govid' => 'Aadhar',
                'idno' => '345612789012',
                'adhar_pic' => null,
                'bank_acc_no' => '234567890123',
                'bank_name' => 'ICICI Bank',
                'ifsc_code' => 'ICIC0002345',
                'passbook_pic' => null,
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'otp' => null,
                'otp_expiry' => null,
            ],

            [
                'id' => 4,
                'first_name' => 'Manish',
                'last_name' => 'Singh',
                'phone' => '7039553407',
                'email' => 'manish.singh@example.com',
                'dob' => '1996-06-18',
                'gender' => 'Male',
                'current_address' => 'Vaishali Nagar',
                'city' => 'Jaipur',
                'state' => 'Rajasthan',
                'country' => 'India',
                'pincode' => '302021',
                'employment_type' => 'Full-Time',
                'joining_date' => '2022-11-22',
                'assigned_area' => 'ABC',
                'vehicle_type' => 'Scooter',
                'vehical_no' => 'RJ14JK9876',
                'driving_license_no' => 'RJDL12349876',
                'driving_license' => null,
                'police_verification' => 'Yes',
                'police_verification_status' => 'Completed',
                'police_certificate' => null,
                'govid' => 'Aadhar',
                'idno' => '987654321012',
                'adhar_pic' => null,
                'bank_acc_no' => '789012345678',
                'bank_name' => 'Axis Bank',
                'ifsc_code' => 'UTIB0006789',
                'passbook_pic' => null,
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'otp' => null,
                'otp_expiry' => null,
            ],

            [
                'id' => 5,
                'first_name' => 'Arjun',
                'last_name' => 'Nair',
                'phone' => '9123456780',
                'email' => 'arjun.nair@example.com',
                'dob' => '1993-03-10',
                'gender' => 'Male',
                'current_address' => 'Kochi Central',
                'city' => 'Kochi',
                'state' => 'Kerala',
                'country' => 'India',
                'pincode' => '682001',
                'employment_type' => 'Part-Time',
                'joining_date' => '2021-07-15',
                'assigned_area' => 'ABC',
                'vehicle_type' => 'Bike',
                'vehical_no' => 'KL07GH3456',
                'driving_license_no' => 'KLDL54321678',
                'driving_license' => null,
                'police_verification' => 'Yes',
                'police_verification_status' => 'Completed',
                'police_certificate' => null,
                'govid' => 'PAN',
                'idno' => 'FGHIJ7654P',
                'adhar_pic' => null,
                'bank_acc_no' => '456789012345',
                'bank_name' => 'Canara Bank',
                'ifsc_code' => 'CNRB0002345',
                'passbook_pic' => null,
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'otp' => null,
                'otp_expiry' => null,
            ],

        ]);
    }
}
