<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EngineerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('engineers')->insert([
            [
                'first_name' => 'Roshan',
                'last_name' => 'Yadav',
                'phone' => '8928339535',
                'email' => 'roshan.yadav@example.com',
                'dob' => '1990-05-15',
                'gender' => 'Male',
                'address' => '123 MG Road',
                'address2' => 'Apt 12B',
                'city' => 'Mumbai',
                'state' => 'Maharashtra',
                'country' => 'India',
                'pincode' => '400001',
                'bank_acc_holder_name' => 'Roshan Yadav',
                'bank_acc_number' => '123456789012',
                'bank_name' => 'State Bank of India',
                'ifsc_code' => 'SBIN0001234',
                'police_verification' => 'Yes',
                'police_verification_status' => 'Pending',
                'police_certificate' => 'roshan_yadav_police.pdf',
                'designation' => 'Network Engineer',
                'department' => 'Installation',
                'join_date' => '2020-06-01',
                'primary_skills' => 'Network Engineer',
                'pic' => 'roshan.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'first_name' => 'Priya',
                'last_name' => 'Patel',
                'phone' => '9123456789',
                'email' => 'priya.patel@example.com',
                'dob' => '1992-09-10',
                'gender' => 'Female',
                'address' => '45 Park Street',
                'address2' => 'Flat 2A',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'country' => 'India',
                'pincode' => '380015',
                'bank_acc_holder_name' => 'Priya Patel',
                'bank_acc_number' => '234567890123',
                'bank_name' => 'HDFC Bank',
                'ifsc_code' => 'HDFC0002345',
                'police_verification' => 'Yes',
                'police_verification_status' => 'Pending',
                'police_certificate' => 'priya_patel_police.pdf',
                'designation' => 'Network Engineer',
                'department' => 'Installation',
                'join_date' => '2021-02-15',
                'primary_skills' => 'Network Engineer',
                'pic' => 'priya.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'first_name' => 'Amit',
                'last_name' => 'Kumar',
                'phone' => '9988776655',
                'email' => 'amit.kumar@example.com',
                'dob' => '1988-12-25',
                'gender' => 'Male',
                'address' => '78 Nehru Nagar',
                'address2' => 'Block C',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'country' => 'India',
                'pincode' => '560034',
                'bank_acc_holder_name' => 'Amit Kumar',
                'bank_acc_number' => '345678901234',
                'bank_name' => 'ICICI Bank',
                'ifsc_code' => 'ICIC0003456',
                'police_verification' => 'Yes',
                'police_verification_status' => 'Pending',
                'police_certificate' => '',
                'designation' => 'Network Engineer',
                'department' => 'Installation',
                'join_date' => '2019-11-20',
                'primary_skills' => 'Network Engineer',
                'pic' => 'amit.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'first_name' => 'Sneha',
                'last_name' => 'Reddy',
                'phone' => '9012345678',
                'email' => 'sneha.reddy@example.com',
                'dob' => '1995-07-30',
                'gender' => 'Female',
                'address' => '56 MG Road',
                'address2' => '3rd Floor',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'country' => 'India',
                'pincode' => '500081',
                'bank_acc_holder_name' => 'Sneha Reddy',
                'bank_acc_number' => '456789012345',
                'bank_name' => 'Axis Bank',
                'ifsc_code' => 'UTIB0004567',
                'police_verification' => 'No',
                'police_verification_status' => 'Pending',
                'police_certificate' => '',
                'designation' => 'Network Engineer',
                'department' => 'Installation',
                'join_date' => '2022-01-10',
                'primary_skills' => 'Network Engineer',
                'pic' => 'sneha.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'first_name' => 'Vikram',
                'last_name' => 'Singh',
                'phone' => '9876501234',
                'email' => 'vikram.singh@example.com',
                'dob' => '1991-03-18',
                'gender' => 'Male',
                'address' => '12 Ashoka Road',
                'address2' => 'Suite 101',
                'city' => 'Delhi',
                'state' => 'Delhi',
                'country' => 'India',
                'pincode' => '110001',
                'bank_acc_holder_name' => 'Vikram Singh',
                'bank_acc_number' => '567890123456',
                'bank_name' => 'Punjab National Bank',
                'ifsc_code' => 'PUNB0005678',
                'police_verification' => 'Yes',
                'police_verification_status' => 'Pending',
                'police_certificate' => 'vikram_singh_police.pdf',
                'designation' => 'Network Engineer',
                'department' => 'Installation',
                'join_date' => '2018-08-05',
                'primary_skills' => 'Network Engineer',
                'pic' => 'vikram.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ]
        ]);
    }
}
