<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $now = Carbon::now();

        DB::table('products')->insert([
            [
                'vendor_name' => 'Technofra',
                'po_number' => '7895',
                'invoice_number' => '376',
                'invoice_pdf' => 'uploads/products/documents/invoice1.pdf',
                'purchase_date' => '2025-10-02',
                'bill_due_date' => '2025-10-02',
                'bill_amount' => 500000.00,
                'product_name' => 'DELL 15 Intel Core i3 13th Gen 1305U',
                'hsn_code' => 'HSN789',
                'sku' => 'SKU48751',
                'brand_id' => 5,
                'model_no' => '35110',
                'serial_no' => 'SN1001',
                'parent_category_id' => 3,
                'sub_category_id' => 7,
                'short_description' => '<p>Short description of DELL 15 Laptop</p>',
                'full_description' => '<p>Full description with features and specifications.</p>',
                'technical_specification' => '<p>Technical specs: Intel i3, 8GB RAM, 512GB SSD.</p>',
                'brand_warranty' => 1,
                'cost_price' => 38000.00,
                'discount_price' => 500.00,
                'tax' => 18.00,
                'selling_price' => 42000.00,
                'final_price' => 49060.00,
                'stock_quantity' => 5,
                'stock_status' => 'In Stock',
                'warehouse_id' => 2,
                'warehouse_rack_id' => 4,
                'rack_zone_area' => 'A',
                'rack_no' => 101,
                'level_no' => 1,
                'position_no' => 1,
                'main_product_image' => 'uploads/warehouse/products/2-4-1.png',
                'additional_product_images' => json_encode(['uploads/warehouse/products/2-4-2.png']),
                'datasheet_manual' => 'uploads/products/documents/datasheet1.pdf',
                'variation_options' => json_encode(['1' => ['1', '5'], '2' => ['7', '8']]),
                'status' => 'Active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'vendor_name' => 'Technofra',
                'po_number' => '7896',
                'invoice_number' => '377',
                'invoice_pdf' => 'uploads/products/documents/invoice2.pdf',
                'purchase_date' => '2025-09-15',
                'bill_due_date' => '2025-09-20',
                'bill_amount' => 750000.00,
                'product_name' => 'HP Pavilion Gaming Laptop',
                'hsn_code' => 'HSN790',
                'sku' => 'SKU48752',
                'brand_id' => 1,
                'model_no' => 'HPG350',
                'serial_no' => 'SN1002',
                'parent_category_id' => 3,
                'sub_category_id' => 6,
                'short_description' => '<p>HP Pavilion Gaming Laptop</p>',
                'full_description' => '<p>Powerful gaming laptop with RTX graphics.</p>',
                'technical_specification' => '<p>Intel i7, 16GB RAM, 1TB SSD.</p>',
                'brand_warranty' => 1,
                'cost_price' => 62000.00,
                'discount_price' => 1000.00,
                'tax' => 18.00,
                'selling_price' => 68500.00,
                'final_price' => 79830.00,
                'stock_quantity' => 10,
                'stock_status' => 'In Stock',
                'warehouse_id' => 1,
                'warehouse_rack_id' => 1,
                'rack_zone_area' => 'B',
                'rack_no' => 102,
                'level_no' => 1,
                'position_no' => 2,
                'main_product_image' => 'uploads/warehouse/products/2-4-1.png',
                'additional_product_images' => json_encode(['uploads/warehouse/products/2-4-2.png']),
                'datasheet_manual' => 'uploads/products/documents/datasheet2.pdf',
                'variation_options' => json_encode(['1' => ['1', '2'], '2' => ['3', '4']]),
                'status' => 'Active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Repeat similar structure for 8 more products
            [
                'vendor_name' => 'Technofra',
                'po_number' => '7897',
                'invoice_number' => '378',
                'invoice_pdf' => 'uploads/products/documents/invoice3.pdf',
                'purchase_date' => '2025-09-18',
                'bill_due_date' => '2025-09-25',
                'bill_amount' => 600000.00,
                'product_name' => 'Asus ZenBook 14',
                'hsn_code' => 'HSN791',
                'sku' => 'SKU48753',
                'brand_id' => 3,
                'model_no' => 'AZ140',
                'serial_no' => 'SN1003',
                'parent_category_id' => 3,
                'sub_category_id' => 7,
                'short_description' => '<p>Lightweight ultrabook</p>',
                'full_description' => '<p>Asus ZenBook 14 with sleek design and powerful performance.</p>',
                'technical_specification' => '<p>Intel i5, 8GB RAM, 256GB SSD.</p>',
                'brand_warranty' => 1,
                'cost_price' => 52500.00,
                'discount_price' => 750.00,
                'tax' => 18.00,
                'selling_price' => 57000.00,
                'final_price' => 66510.00,
                'stock_quantity' => 8,
                'stock_status' => 'In Stock',
                'warehouse_id' => 3,
                'warehouse_rack_id' => 5,
                'rack_zone_area' => 'C',
                'rack_no' => 301,
                'level_no' => 1,
                'position_no' => 3,
                'main_product_image' => 'uploads/warehouse/products/2-4-1.png',
                'additional_product_images' => json_encode(['uploads/warehouse/products/2-4-2.png']),
                'datasheet_manual' => 'uploads/products/documents/datasheet3.pdf',
                'variation_options' => json_encode(['1' => ['1', '3'], '2' => ['5', '6']]),
                'status' => 'Active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'vendor_name' => 'Technofra',
                'po_number' => '7898',
                'invoice_number' => '379',
                'invoice_pdf' => 'uploads/products/documents/invoice4.pdf',
                'purchase_date' => '2025-09-20',
                'bill_due_date' => '2025-09-28',
                'bill_amount' => 450000.00,
                'product_name' => 'Dell Inspiron 16',
                'hsn_code' => 'HSN792',
                'sku' => 'SKU48754',
                'brand_id' => 5,
                'model_no' => 'DI160',
                'serial_no' => 'SN1004',
                'parent_category_id' => 3,
                'sub_category_id' => 7,
                'short_description' => '<p>16-inch display laptop</p>',
                'full_description' => '<p>Dell Inspiron 16 with Intel i5 processor and 512GB SSD.</p>',
                'technical_specification' => '<p>Intel i5, 8GB RAM, 512GB SSD.</p>',
                'brand_warranty' => 1,
                'cost_price' => 44000.00,
                'discount_price' => 600.00,
                'tax' => 18.00,
                'selling_price' => 48200.00,
                'final_price' => 56276.00,
                'stock_quantity' => 6,
                'stock_status' => 'In Stock',
                'warehouse_id' => 4,
                'warehouse_rack_id' => 6,
                'rack_zone_area' => 'D',
                'rack_no' => 401,
                'level_no' => 1,
                'position_no' => 4,
                'main_product_image' => 'uploads/warehouse/products/2-4-1.png',
                'additional_product_images' => json_encode(['uploads/warehouse/products/2-4-2.png']),
                'datasheet_manual' => 'uploads/products/documents/datasheet4.pdf',
                'variation_options' => json_encode(['1' => ['2', '4'], '2' => ['6', '8']]),
                'status' => 'Active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'vendor_name' => 'Technofra',
                'po_number' => '7899',
                'invoice_number' => '380',
                'invoice_pdf' => 'uploads/products/documents/invoice5.pdf',
                'purchase_date' => '2025-09-22',
                'bill_due_date' => '2025-09-30',
                'bill_amount' => 300000.00,
                'product_name' => 'HP EliteBook 840',
                'hsn_code' => 'HSN793',
                'sku' => 'SKU48755',
                'brand_id' => 1,
                'model_no' => 'HE840',
                'serial_no' => 'SN1005',
                'parent_category_id' => 3,
                'sub_category_id' => 6,
                'short_description' => '<p>Business ultrabook</p>',
                'full_description' => '<p>HP EliteBook 840 with security features.</p>',
                'technical_specification' => '<p>Intel i5, 8GB RAM, 256GB SSD.</p>',
                'brand_warranty' => 1,
                'cost_price' => 71000.00,
                'discount_price' => 1200.00,
                'tax' => 18.00,
                'selling_price' => 78000.00,
                'final_price' => 90840.00,
                'stock_quantity' => 4,
                'stock_status' => 'In Stock',
                'warehouse_id' => 5,
                'warehouse_rack_id' => 7,
                'rack_zone_area' => 'E',
                'rack_no' => 501,
                'level_no' => 1,
                'position_no' => 5,
                'main_product_image' => 'uploads/warehouse/products/2-4-1.png',
                'additional_product_images' => json_encode(['uploads/warehouse/products/2-4-2.png']),
                'datasheet_manual' => 'uploads/products/documents/datasheet5.pdf',
                'variation_options' => json_encode(['1' => ['3', '5'], '2' => ['7', '9']]),
                'status' => 'Active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // You can continue adding 5 more products with similar structure

            // Spare Part  
            [
                'vendor_name' => 'Technofra',
                'po_number' => '7900',
                'invoice_number' => '381',
                'invoice_pdf' => 'uploads/products/documents/invoice6.pdf',
                'purchase_date' => '2025-10-05',
                'bill_due_date' => '2025-10-10',
                'bill_amount' => 85000.00,
                'product_name' => 'Laptop Battery for Dell Inspiron',
                'hsn_code' => 'HSN794',
                'sku' => 'SKU48756',
                'brand_id' => 5,
                'model_no' => 'LB-DI100',
                'serial_no' => 'SN1006',
                'parent_category_id' => 13,
                'sub_category_id' => 2,
                'short_description' => '<p>Replacement battery for Dell Inspiron series</p>',
                'full_description' => '<p>High-performance Lithium-ion 6-cell battery compatible with multiple Dell models.</p>',
                'technical_specification' => '<p>11.1V, 4400mAh capacity, OEM grade cells.</p>',
                'brand_warranty' => 1,
                'cost_price' => 5800.00,
                'discount_price' => 200.00,
                'tax' => 18.00,
                'selling_price' => 6400.00,
                'final_price' => 7552.00,
                'stock_quantity' => 15,
                'stock_status' => 'In Stock',
                'warehouse_id' => 2,
                'warehouse_rack_id' => 3,
                'rack_zone_area' => 'F',
                'rack_no' => 201,
                'level_no' => 1,
                'position_no' => 6,
                'main_product_image' => 'uploads/warehouse/products/Spare Part.png',
                'additional_product_images' => json_encode(['uploads/warehouse/products/Spare Part.png']),
                'datasheet_manual' => 'uploads/products/documents/datasheet6.pdf',
                'variation_options' => json_encode(['1' => ['2', '3'], '2' => ['4', '5']]),
                'status' => 'Active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'vendor_name' => 'Technofra',
                'po_number' => '7901',
                'invoice_number' => '382',
                'invoice_pdf' => 'uploads/products/documents/invoice7.pdf',
                'purchase_date' => '2025-10-07',
                'bill_due_date' => '2025-10-12',
                'bill_amount' => 120000.00,
                'product_name' => 'HP Adapter 65W Original',
                'hsn_code' => 'HSN795',
                'sku' => 'SKU48757',
                'brand_id' => 1,
                'model_no' => 'HPAD65',
                'serial_no' => 'SN1007',
                'parent_category_id' => 13,
                'sub_category_id' => 1,
                'short_description' => '<p>65W original HP laptop adapter</p>',
                'full_description' => '<p>Reliable power adapter compatible with HP Pavilion and EliteBook series.</p>',
                'technical_specification' => '<p>65W, 19.5V, 3.33A, 4.5mm pin.</p>',
                'brand_warranty' => 1,
                'cost_price' => 2300.00,
                'discount_price' => 100.00,
                'tax' => 18.00,
                'selling_price' => 2600.00,
                'final_price' => 3068.00,
                'stock_quantity' => 25,
                'stock_status' => 'In Stock',
                'warehouse_id' => 1,
                'warehouse_rack_id' => 2,
                'rack_zone_area' => 'A',
                'rack_no' => 103,
                'level_no' => 1,
                'position_no' => 7,
                'main_product_image' => 'uploads/warehouse/products/Spare Part.png',
                'additional_product_images' => json_encode(['uploads/warehouse/products/Spare Part.png']),
                'datasheet_manual' => 'uploads/products/documents/datasheet7.pdf',
                'variation_options' => json_encode(['1' => ['1', '3'], '2' => ['5', '7']]),
                'status' => 'Active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'vendor_name' => 'Technofra',
                'po_number' => '7902',
                'invoice_number' => '383',
                'invoice_pdf' => 'uploads/products/documents/invoice8.pdf',
                'purchase_date' => '2025-10-08',
                'bill_due_date' => '2025-10-14',
                'bill_amount' => 50000.00,
                'product_name' => 'Lenovo Laptop Keyboard',
                'hsn_code' => 'HSN796',
                'sku' => 'SKU48758',
                'brand_id' => 2,
                'model_no' => 'LK-LNV01',
                'serial_no' => 'SN1008',
                'parent_category_id' => 13,
                'sub_category_id' => 1,
                'short_description' => '<p>Original Lenovo replacement keyboard</p>',
                'full_description' => '<p>Backlit keyboard suitable for Lenovo ThinkBook and IdeaPad series.</p>',
                'technical_specification' => '<p>QWERTY, backlit, spill-resistant.</p>',
                'brand_warranty' => 1,
                'cost_price' => 1800.00,
                'discount_price' => 50.00,
                'tax' => 18.00,
                'selling_price' => 2100.00,
                'final_price' => 2479.00,
                'stock_quantity' => 30,
                'stock_status' => 'In Stock',
                'warehouse_id' => 3,
                'warehouse_rack_id' => 5,
                'rack_zone_area' => 'B',
                'rack_no' => 302,
                'level_no' => 2,
                'position_no' => 8,
                'main_product_image' => 'uploads/warehouse/products/Spare Part.png',
                'additional_product_images' => json_encode(['uploads/warehouse/products/Spare Part.png']),
                'datasheet_manual' => 'uploads/products/documents/datasheet8.pdf',
                'variation_options' => json_encode(['1' => ['2', '5'], '2' => ['6', '8']]),
                'status' => 'Active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'vendor_name' => 'Technofra',
                'po_number' => '7903',
                'invoice_number' => '384',
                'invoice_pdf' => 'uploads/products/documents/invoice9.pdf',
                'purchase_date' => '2025-10-10',
                'bill_due_date' => '2025-10-15',
                'bill_amount' => 40000.00,
                'product_name' => 'Laptop Cooling Fan for HP Pavilion',
                'hsn_code' => 'HSN797',
                'sku' => 'SKU48759',
                'brand_id' => 1,
                'model_no' => 'HPCF450',
                'serial_no' => 'SN1009',
                'parent_category_id' => 13,
                'sub_category_id' => 1,
                'short_description' => '<p>Cooling fan replacement for HP Pavilion models</p>',
                'full_description' => '<p>Durable and quiet cooling fan designed for efficient heat dissipation.</p>',
                'technical_specification' => '<p>Voltage: 5V, Speed: 5400RPM, Copper bearings.</p>',
                'brand_warranty' => 0,
                'cost_price' => 1200.00,
                'discount_price' => 30.00,
                'tax' => 18.00,
                'selling_price' => 1400.00,
                'final_price' => 1652.00,
                'stock_quantity' => 40,
                'stock_status' => 'In Stock',
                'warehouse_id' => 4,
                'warehouse_rack_id' => 6,
                'rack_zone_area' => 'C',
                'rack_no' => 402,
                'level_no' => 1,
                'position_no' => 9,
                'main_product_image' => 'uploads/warehouse/products/Spare Part.png',
                'additional_product_images' => json_encode(['uploads/warehouse/products/Spare Part.png']),
                'datasheet_manual' => 'uploads/products/documents/datasheet9.pdf',
                'variation_options' => json_encode(['1' => ['1', '2'], '2' => ['3', '4']]),
                'status' => 'Active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'vendor_name' => 'Technofra',
                'po_number' => '7904',
                'invoice_number' => '385',
                'invoice_pdf' => 'uploads/products/documents/invoice10.pdf',
                'purchase_date' => '2025-10-12',
                'bill_due_date' => '2025-10-18',
                'bill_amount' => 95000.00,
                'product_name' => 'Asus 512GB SSD Replacement',
                'hsn_code' => 'HSN798',
                'sku' => 'SKU48760',
                'brand_id' => 3,
                'model_no' => 'A512SSD',
                'serial_no' => 'SN1010',
                'parent_category_id' => 13,
                'sub_category_id' => 3,
                'short_description' => '<p>512GB M.2 SSD for Asus laptops</p>',
                'full_description' => '<p>High-speed NVMe SSD providing rapid read and write speeds for Asus laptops.</p>',
                'technical_specification' => '<p>PCIe Gen3, read speed 3500MB/s, write speed 3100MB/s.</p>',
                'brand_warranty' => 1,
                'cost_price' => 4500.00,
                'discount_price' => 150.00,
                'tax' => 18.00,
                'selling_price' => 4900.00,
                'final_price' => 5782.00,
                'stock_quantity' => 20,
                'stock_status' => 'In Stock',
                'warehouse_id' => 5,
                'warehouse_rack_id' => 7,
                'rack_zone_area' => 'D',
                'rack_no' => 502,
                'level_no' => 2,
                'position_no' => 10,
                'main_product_image' => 'uploads/warehouse/products/Spare Part.png',
                'additional_product_images' => json_encode(['uploads/warehouse/products/Spare Part.png']),
                'datasheet_manual' => 'uploads/products/documents/datasheet10.pdf',
                'variation_options' => json_encode(['1' => ['4', '6'], '2' => ['7', '9']]),
                'status' => 'Active',
                'created_at' => $now,
                'updated_at' => $now,
            ],

        ]);
    }
}
