<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $now = Carbon::now();

        DB::table('products')->insert([
            [
                'vendor_name' => 'Technofra',
                'po_number' => '7895',
                'invoice_number' => '376',
                'invoice_pdf' => 'uploads/products/documents/invoice1.pdf',
                'purchase_date' => '2025-10-02',
                'bill_due_date' => '2025-10-02',
                'bill_amount' => 500000.00,
                'product_name' => 'DELL 15 Intel Core i3 13th Gen 1305U',
                'hsn_code' => 'HSN789',
                'sku' => 'SKU48751',
                'brand_id' => 5,
                'model_no' => '35110',
                'serial_no' => 'SN1001',
                'parent_category_id' => 3,
                'sub_category_id' => 7,
                'short_description' => '<p>Short description of DELL 15 Laptop</p>',
                'full_description' => '<p>Full description with features and specifications.</p>',
                'technical_specification' => '<p>Technical specs: Intel i3, 8GB RAM, 512GB SSD.</p>',
                'brand_warranty' => 1,
                'cost_price' => 54479.00,
                'discount_price' => 500.00,
                'tax' => 18.00,
                'selling_price' => 37990.00,
                'final_price' => 44238.20,
                'stock_quantity' => 5,
                'stock_status' => 'In Stock',
                'warehouse_id' => 2,
                'warehouse_rack_id' => 4,
                'rack_zone_area' => 'A',
                'rack_no' => 101,
                'level_no' => 1,
                'position_no' => 1,
                'main_product_image' => 'uploads/products/images/main1.png',
                'additional_product_images' => json_encode(['uploads/products/images/add1.png','uploads/products/images/add2.png']),
                'datasheet_manual' => 'uploads/products/documents/datasheet1.pdf',
                'variation_options' => json_encode(['1'=>['1','5'],'2'=>['7','8']]),
                'status' => 'Active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'vendor_name' => 'Technofra',
                'po_number' => '7896',
                'invoice_number' => '377',
                'invoice_pdf' => 'uploads/products/documents/invoice2.pdf',
                'purchase_date' => '2025-09-15',
                'bill_due_date' => '2025-09-20',
                'bill_amount' => 750000.00,
                'product_name' => 'HP Pavilion Gaming Laptop',
                'hsn_code' => 'HSN790',
                'sku' => 'SKU48752',
                'brand_id' => 1,
                'model_no' => 'HPG350',
                'serial_no' => 'SN1002',
                'parent_category_id' => 3,
                'sub_category_id' => 6,
                'short_description' => '<p>HP Pavilion Gaming Laptop</p>',
                'full_description' => '<p>Powerful gaming laptop with RTX graphics.</p>',
                'technical_specification' => '<p>Intel i7, 16GB RAM, 1TB SSD.</p>',
                'brand_warranty' => 1,
                'cost_price' => 700000.00,
                'discount_price' => 1000.00,
                'tax' => 18.00,
                'selling_price' => 680000.00,
                'final_price' => 802400.00,
                'stock_quantity' => 10,
                'stock_status' => 'In Stock',
                'warehouse_id' => 1,
                'warehouse_rack_id' => 1,
                'rack_zone_area' => 'B',
                'rack_no' => 102,
                'level_no' => 1,
                'position_no' => 2,
                'main_product_image' => 'uploads/products/images/main2.png',
                'additional_product_images' => json_encode(['uploads/products/images/add3.png','uploads/products/images/add4.png']),
                'datasheet_manual' => 'uploads/products/documents/datasheet2.pdf',
                'variation_options' => json_encode(['1'=>['1','2'],'2'=>['3','4']]),
                'status' => 'Active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Repeat similar structure for 8 more products
            [
                'vendor_name' => 'Technofra',
                'po_number' => '7897',
                'invoice_number' => '378',
                'invoice_pdf' => 'uploads/products/documents/invoice3.pdf',
                'purchase_date' => '2025-09-18',
                'bill_due_date' => '2025-09-25',
                'bill_amount' => 600000.00,
                'product_name' => 'Asus ZenBook 14',
                'hsn_code' => 'HSN791',
                'sku' => 'SKU48753',
                'brand_id' => 3,
                'model_no' => 'AZ140',
                'serial_no' => 'SN1003',
                'parent_category_id' => 3,
                'sub_category_id' => 7,
                'short_description' => '<p>Lightweight ultrabook</p>',
                'full_description' => '<p>Asus ZenBook 14 with sleek design and powerful performance.</p>',
                'technical_specification' => '<p>Intel i5, 8GB RAM, 256GB SSD.</p>',
                'brand_warranty' => 1,
                'cost_price' => 580000.00,
                'discount_price' => 800.00,
                'tax' => 18.00,
                'selling_price' => 570000.00,
                'final_price' => 672600.00,
                'stock_quantity' => 8,
                'stock_status' => 'In Stock',
                'warehouse_id' => 3,
                'warehouse_rack_id' => 5,
                'rack_zone_area' => 'C',
                'rack_no' => 301,
                'level_no' => 1,
                'position_no' => 3,
                'main_product_image' => 'uploads/products/images/main3.png',
                'additional_product_images' => json_encode(['uploads/products/images/add5.png','uploads/products/images/add6.png']),
                'datasheet_manual' => 'uploads/products/documents/datasheet3.pdf',
                'variation_options' => json_encode(['1'=>['1','3'],'2'=>['5','6']]),
                'status' => 'Active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'vendor_name' => 'Technofra',
                'po_number' => '7898',
                'invoice_number' => '379',
                'invoice_pdf' => 'uploads/products/documents/invoice4.pdf',
                'purchase_date' => '2025-09-20',
                'bill_due_date' => '2025-09-28',
                'bill_amount' => 450000.00,
                'product_name' => 'Dell Inspiron 16',
                'hsn_code' => 'HSN792',
                'sku' => 'SKU48754',
                'brand_id' => 5,
                'model_no' => 'DI160',
                'serial_no' => 'SN1004',
                'parent_category_id' => 3,
                'sub_category_id' => 7,
                'short_description' => '<p>16-inch display laptop</p>',
                'full_description' => '<p>Dell Inspiron 16 with Intel i5 processor and 512GB SSD.</p>',
                'technical_specification' => '<p>Intel i5, 8GB RAM, 512GB SSD.</p>',
                'brand_warranty' => 1,
                'cost_price' => 430000.00,
                'discount_price' => 700.00,
                'tax' => 18.00,
                'selling_price' => 420000.00,
                'final_price' => 495600.00,
                'stock_quantity' => 6,
                'stock_status' => 'In Stock',
                'warehouse_id' => 4,
                'warehouse_rack_id' => 6,
                'rack_zone_area' => 'D',
                'rack_no' => 401,
                'level_no' => 1,
                'position_no' => 4,
                'main_product_image' => 'uploads/products/images/main4.png',
                'additional_product_images' => json_encode(['uploads/products/images/add7.png','uploads/products/images/add8.png']),
                'datasheet_manual' => 'uploads/products/documents/datasheet4.pdf',
                'variation_options' => json_encode(['1'=>['2','4'],'2'=>['6','8']]),
                'status' => 'Active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'vendor_name' => 'Technofra',
                'po_number' => '7899',
                'invoice_number' => '380',
                'invoice_pdf' => 'uploads/products/documents/invoice5.pdf',
                'purchase_date' => '2025-09-22',
                'bill_due_date' => '2025-09-30',
                'bill_amount' => 300000.00,
                'product_name' => 'HP EliteBook 840',
                'hsn_code' => 'HSN793',
                'sku' => 'SKU48755',
                'brand_id' => 1,
                'model_no' => 'HE840',
                'serial_no' => 'SN1005',
                'parent_category_id' => 3,
                'sub_category_id' => 6,
                'short_description' => '<p>Business ultrabook</p>',
                'full_description' => '<p>HP EliteBook 840 with security features.</p>',
                'technical_specification' => '<p>Intel i5, 8GB RAM, 256GB SSD.</p>',
                'brand_warranty' => 1,
                'cost_price' => 280000.00,
                'discount_price' => 500.00,
                'tax' => 18.00,
                'selling_price' => 275000.00,
                'final_price' => 324500.00,
                'stock_quantity' => 4,
                'stock_status' => 'In Stock',
                'warehouse_id' => 5,
                'warehouse_rack_id' => 7,
                'rack_zone_area' => 'E',
                'rack_no' => 501,
                'level_no' => 1,
                'position_no' => 5,
                'main_product_image' => 'uploads/products/images/main5.png',
                'additional_product_images' => json_encode(['uploads/products/images/add9.png','uploads/products/images/add10.png']),
                'datasheet_manual' => 'uploads/products/documents/datasheet5.pdf',
                'variation_options' => json_encode(['1'=>['3','5'],'2'=>['7','9']]),
                'status' => 'Active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // You can continue adding 5 more products with similar structure
        ]);
    }
}
