<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class SalesPeopleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('sales_people')->insert([

            [
                'id' => 1,
                'first_name' => 'Manish',
                'last_name' => 'Singh',
                'phone' => '7039553407',
                'email' => 'manish.singh@example.com',
                'dob' => '1991-05-10',
                'gender' => 'Male',
                'current_address' => 'Goregaon East',
                'city' => 'Mumbai',
                'state' => 'Maharashtra',
                'country' => 'India',
                'pincode' => '400063',
                'employment_type' => 'Full-Time',
                'joining_date' => '2021-08-10',
                'assigned_area' => 'ABC',
                'vehicle_type' => 'Bike',
                'vehical_no' => 'MH01AB2345',
                'driving_license_no' => 'MHDL12345678',
                'driving_license' => null,
                'police_verification' => 'Yes',
                'police_verification_status' => 'Completed',
                'police_certificate' => null,
                'govid' => 'Aadhar',
                'idno' => '123456789012',
                'adhar_pic' => null,
                'bank_acc_no' => '123456789012',
                'bank_name' => 'HDFC Bank',
                'ifsc_code' => 'HDFC0001234',
                'passbook_pic' => null,
                'status' => 1,
                'otp' => null,
                'otp_expiry' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'id' => 2,
                'first_name' => 'Roshan',
                'last_name' => 'Yadav',
                'phone' => '8928339535',
                'email' => 'roshan.yadav@example.com',
                'dob' => '1993-11-18',
                'gender' => 'Male',
                'current_address' => 'Whitefield',
                'city' => 'Bengaluru',
                'state' => 'Karnataka',
                'country' => 'India',
                'pincode' => '560066',
                'employment_type' => 'Part-Time',
                'joining_date' => '2022-04-22',
                'assigned_area' => 'ABC',
                'vehicle_type' => 'Scooter',
                'vehical_no' => 'KA03CD5678',
                'driving_license_no' => 'KADL87654321',
                'driving_license' => null,
                'police_verification' => 'Yes',
                'police_verification_status' => 'Completed',
                'police_certificate' => null,
                'govid' => 'PAN',
                'idno' => 'ABCDE1234F',
                'adhar_pic' => null,
                'bank_acc_no' => '567890123456',
                'bank_name' => 'SBI Bank',
                'ifsc_code' => 'SBIN0004567',
                'passbook_pic' => null,
                'status' => 1,
                'otp' => null,
                'otp_expiry' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'id' => 3,
                'first_name' => 'Saurabh',
                'last_name' => 'Damale',
                'phone' => '7709131547',
                'email' => 'saurabh.damale@example.com',
                'dob' => '1989-02-07',
                'gender' => 'Male',
                'current_address' => 'Banjara Hills',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'country' => 'India',
                'pincode' => '500034',
                'employment_type' => 'Full-Time',
                'joining_date' => '2020-12-10',
                'assigned_area' => 'ABC',
                'vehicle_type' => 'Bike',
                'vehical_no' => 'TS07EF3421',
                'driving_license_no' => 'TSDL23456789',
                'driving_license' => null,
                'police_verification' => 'Yes',
                'police_verification_status' => 'Completed',
                'police_certificate' => null,
                'govid' => 'Aadhar',
                'idno' => '567890123456',
                'adhar_pic' => null,
                'bank_acc_no' => '234567890123',
                'bank_name' => 'ICICI Bank',
                'ifsc_code' => 'ICIC0002345',
                'passbook_pic' => null,
                'status' => 1,
                'otp' => null,
                'otp_expiry' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'id' => 4,
                'first_name' => 'Mayur',
                'last_name' => 'Satam',
                'phone' => '8591483531',
                'email' => 'mayur.satam@example.com',
                'dob' => '1995-06-10',
                'gender' => 'Female',
                'current_address' => 'Malviya Nagar',
                'city' => 'Jaipur',
                'state' => 'Rajasthan',
                'country' => 'India',
                'pincode' => '302017',
                'employment_type' => 'Full-Time',
                'joining_date' => '2023-02-10',
                'assigned_area' => 'ABC',
                'vehicle_type' => 'Scooter',
                'vehical_no' => 'RJ14GH7890',
                'driving_license_no' => 'RJDL34567890',
                'driving_license' => null,
                'police_verification' => 'Yes',
                'police_verification_status' => 'Completed',
                'police_certificate' => null,
                'govid' => 'Aadhar',
                'idno' => '789012345678',
                'adhar_pic' => null,
                'bank_acc_no' => '789012345678',
                'bank_name' => 'Axis Bank',
                'ifsc_code' => 'UTIB0005678',
                'passbook_pic' => null,
                'status' => 1,
                'otp' => null,
                'otp_expiry' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'id' => 5,
                'first_name' => 'Nikhil',
                'last_name' => 'Nair',
                'phone' => '9123456780',
                'email' => 'nikhil.nair@example.com',
                'dob' => '1992-01-25',
                'gender' => 'Male',
                'current_address' => 'Edappally',
                'city' => 'Kochi',
                'state' => 'Kerala',
                'country' => 'India',
                'pincode' => '682024',
                'employment_type' => 'Part-Time',
                'joining_date' => '2022-09-13',
                'assigned_area' => 'ABC',
                'vehicle_type' => 'Bike',
                'vehical_no' => 'KL07JK4567',
                'driving_license_no' => 'KLDL65432178',
                'driving_license' => null,
                'police_verification' => 'Yes',
                'police_verification_status' => 'Completed',
                'police_certificate' => null,
                'govid' => 'PAN',
                'idno' => 'PQRSX9876Q',
                'adhar_pic' => null,
                'bank_acc_no' => '456789012345',
                'bank_name' => 'Canara Bank',
                'ifsc_code' => 'CNRB0003456',
                'passbook_pic' => null,
                'status' => 1,
                'otp' => null,
                'otp_expiry' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

        ]);
    }
}
